headers={"Host": "mightyzeus.housing.com",
"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0",
"Accept": "*/*",
"Accept-Language": "en-US,en;q=0.5",
"Accept-Encoding": "gzip, deflate",
"Referer": "https://housing.com/in/buy/searches/P6xfqdsey6cc3d95h",
"Phoenix-Api-Name": "SEARCH_RESULTS",
"App-Name": "desktop_web_buyer",
"Content-Type": "application/json; charset=UTF-8",
"Origin": "https://housing.com",
"Dnt": "1",
"Sec-Fetch-Dest": "empty",
"Sec-Fetch-Mode": "cors",
"Sec-Fetch-Site": "same-site",
"Te": "trailers",}